map_activities = {
    1: "Combustion",
    2: "Refineries",
    3: "Coke ovens",
    4: "Metal",
    5: "Metal",
    6: "Cement/Lime",
    7: "Glass/Ceramics",
    8: "Glass/Ceramics",
    9: "Pulp/Paper",
    10: "Aircrafts",
    20: "Combustion",
    21: "Refineries",
    22: "Coke ovens",
    23: "Metal",
    24: "Metal",
    25: "Metal",
    26: "Metal",
    27: "Metal",
    28: "Metal",
    29: "Cement/Lime",
    30: "Cement/Lime",
    31: "Glass/Ceramics",
    32: "Glass/Ceramics",
    33: "Glass/Ceramics",
    34: "Glass/Ceramics",
    35: "Pulp/Paper",
    36: "Pulp/Paper",
    37: "Chemicals",
    38: "Chemicals",
    39: "Chemicals",
    40: "Chemicals",
    41: "Chemicals",
    42: "Chemicals",
    43: "Hydrogen Production",
    44: "Chemicals",
    45: "Carbon Capture",
    46: "Carbon Capture",
    47: "Carbon Capture",
    99: "Other"
}

map_activities_inv = {}
for key, val in map_activities.items():
    map_activities_inv[val] = map_activities_inv.get(val, []) + [key]

map_accounts = {"100-7": "Operator Holding Account",
        "100-9": "Operator Holding Account",
        "120-0": "Operator Holding Account",
        "100-8": "Person Holding Account",
        "100-12": "Person Holding Account",
        "121-0": "Person Holding Account",
        "0-10": "Administrative Account",
        "0-11": "Administrative Account",
        "100-0": "Administrative Account",
        "100-1": "Administrative Account",
        "100-2": "Administrative Account",
        "100-3": "Administrative Account",
        "100-4": "Administrative Account",
        "100-5": "Administrative Account",
        "100-6": "Administrative Account",
        "100-13": "Administrative Account",
        "100-14": "Administrative Account",
        "100-15": "Administrative Account",
        "100-16": "Administrative Account",
        "100-17": "Administrative Account",
        "100-18": "Administrative Account",
        "100-19": "Administrative Account",
        "100-20": "Administrative Account",
        "100-21": "Administrative Account",
        "100-22": "Administrative Account",
        "100-23": "Administrative Account",
        "100-24": "Administrative Account",
        "100-25": "Administrative Account",
        "100-26": "Administrative Account",
        "100-27": "Administrative Account",
        "100-28": "Administrative Account",
        "100-29": "Administrative Account",
        "100-30": "Administrative Account",
        "100-31": "Administrative Account",
        "110-0": "Administrative Account",
        "130-0": "Administrative Account",
        "210-0": "Administrative Account",
        "220-0": "Administrative Account",
        "230-0": "Administrative Account",
        "240-0": "Administrative Account",
        "241-0": "Administrative Account",
        "242-0": "Administrative Account",
        "250-0": "Administrative Account",
        "270-0": "Administrative Account",
        "280-0": "Administrative Account",
        "300-0": "Administrative Account",
        "411-0": "Administrative Account",
        "421-0": "Administrative Account",
        "422-0": "Administrative Account",
        "423-0": "Administrative Account",
        "None": "Account Type Not Provided"}

map_accounts_inv = {}
for key, val in map_accounts.items():
    map_accounts_inv[val] = map_accounts_inv.get(val, []) + [key]

map_nace = {"01": "Agriculture and mining",
		"01.0": "Agriculture and mining",
		"01.1": "Agriculture and mining",
		"01.11": "Agriculture and mining",
		"01.12": "Agriculture and mining",
		"01.13": "Agriculture and mining",
		"01.14": "Agriculture and mining",
		"01.15": "Agriculture and mining",
		"01.16": "Agriculture and mining",
		"01.19": "Agriculture and mining",
		"01.2": "Agriculture and mining",
		"01.21": "Agriculture and mining",
		"01.22": "Agriculture and mining",
		"01.23": "Agriculture and mining",
		"01.24": "Agriculture and mining",
		"01.25": "Agriculture and mining",
		"01.26": "Agriculture and mining",
		"01.27": "Agriculture and mining",
		"01.28": "Agriculture and mining",
		"01.29": "Agriculture and mining",
		"01.3": "Agriculture and mining",
		"01.30": "Agriculture and mining",
		"01.4": "Agriculture and mining",
		"01.41": "Agriculture and mining",
		"01.42": "Agriculture and mining",
		"01.43": "Agriculture and mining",
		"01.44": "Agriculture and mining",
		"01.45": "Agriculture and mining",
		"01.46": "Agriculture and mining",
		"01.47": "Agriculture and mining",
		"01.49": "Agriculture and mining",
		"01.5": "Agriculture and mining",
		"01.50": "Agriculture and mining",
		"01.6": "Agriculture and mining",
		"01.61": "Agriculture and mining",
		"01.62": "Agriculture and mining",
		"01.63": "Agriculture and mining",
		"01.64": "Agriculture and mining",
		"01.7": "Agriculture and mining",
		"01.70": "Agriculture and mining",
		"02": "Agriculture and mining",
		"02.0": "Agriculture and mining",
		"02.1": "Agriculture and mining",
		"02.10": "Agriculture and mining",
		"02.2": "Agriculture and mining",
		"02.20": "Agriculture and mining",
		"02.3": "Agriculture and mining",
		"02.30": "Agriculture and mining",
		"02.4": "Agriculture and mining",
		"02.40": "Agriculture and mining",
		"03": "Agriculture and mining",
		"03.0": "Agriculture and mining",
		"03.1": "Agriculture and mining",
		"03.11": "Agriculture and mining",
		"03.12": "Agriculture and mining",
		"03.2": "Agriculture and mining",
		"03.21": "Agriculture and mining",
		"03.22": "Agriculture and mining",
		"05": "Agriculture and mining",
		"05.0": "Agriculture and mining",
		"05.1": "Agriculture and mining",
		"05.10": "Agriculture and mining",
		"05.2": "Agriculture and mining",
		"05.20": "Agriculture and mining",
		"06": "Agriculture and mining",
		"06.0": "Agriculture and mining",
		"06.1": "Agriculture and mining",
		"06.10": "Agriculture and mining",
		"06.2": "Agriculture and mining",
		"06.20": "Agriculture and mining",
		"07": "Agriculture and mining",
		"07.0": "Agriculture and mining",
		"07.1": "Agriculture and mining",
		"07.10": "Agriculture and mining",
		"07.2": "Agriculture and mining",
		"07.21": "Agriculture and mining",
		"07.29": "Agriculture and mining",
		"08": "Agriculture and mining",
		"08.0": "Agriculture and mining",
		"08.1": "Agriculture and mining",
		"08.11": "Agriculture and mining",
		"08.12": "Agriculture and mining",
		"08.9": "Agriculture and mining",
		"08.91": "Agriculture and mining",
		"08.92": "Agriculture and mining",
		"08.93": "Agriculture and mining",
		"08.99": "Agriculture and mining",
		"09": "Agriculture and mining",
		"09.0": "Agriculture and mining",
		"09.1": "Agriculture and mining",
		"09.10": "Agriculture and mining",
		"09.9": "Agriculture and mining",
		"09.90": "Agriculture and mining",
		"10": "Manufacturing: Food, beverages, tabacco",
		"10.0": "Manufacturing: Food, beverages, tabacco",
		"10.1": "Manufacturing: Food, beverages, tabacco",
		"10.11": "Manufacturing: Food, beverages, tabacco",
		"10.12": "Manufacturing: Food, beverages, tabacco",
		"10.13": "Manufacturing: Food, beverages, tabacco",
		"10.2": "Manufacturing: Food, beverages, tabacco",
		"10.20": "Manufacturing: Food, beverages, tabacco",
		"10.3": "Manufacturing: Food, beverages, tabacco",
		"10.31": "Manufacturing: Food, beverages, tabacco",
		"10.32": "Manufacturing: Food, beverages, tabacco",
		"10.39": "Manufacturing: Food, beverages, tabacco",
		"10.4": "Manufacturing: Food, beverages, tabacco",
		"10.41": "Manufacturing: Food, beverages, tabacco",
		"10.42": "Manufacturing: Food, beverages, tabacco",
		"10.5": "Manufacturing: Food, beverages, tabacco",
		"10.51": "Manufacturing: Food, beverages, tabacco",
		"10.52": "Manufacturing: Food, beverages, tabacco",
		"10.6": "Manufacturing: Food, beverages, tabacco",
		"10.61": "Manufacturing: Food, beverages, tabacco",
		"10.62": "Manufacturing: Food, beverages, tabacco",
		"10.7": "Manufacturing: Food, beverages, tabacco",
		"10.71": "Manufacturing: Food, beverages, tabacco",
		"10.72": "Manufacturing: Food, beverages, tabacco",
		"10.73": "Manufacturing: Food, beverages, tabacco",
		"10.8": "Manufacturing: Food, beverages, tabacco",
		"10.81": "Manufacturing: Food, beverages, tabacco",
		"10.82": "Manufacturing: Food, beverages, tabacco",
		"10.83": "Manufacturing: Food, beverages, tabacco",
		"10.84": "Manufacturing: Food, beverages, tabacco",
		"10.85": "Manufacturing: Food, beverages, tabacco",
		"10.86": "Manufacturing: Food, beverages, tabacco",
		"10.89": "Manufacturing: Food, beverages, tabacco",
		"10.9": "Manufacturing: Food, beverages, tabacco",
		"10.91": "Manufacturing: Food, beverages, tabacco",
		"10.92": "Manufacturing: Food, beverages, tabacco",
		"11": "Manufacturing: Food, beverages, tabacco",
		"11.0": "Manufacturing: Food, beverages, tabacco",
		"11.01": "Manufacturing: Food, beverages, tabacco",
		"11.02": "Manufacturing: Food, beverages, tabacco",
		"11.03": "Manufacturing: Food, beverages, tabacco",
		"11.04": "Manufacturing: Food, beverages, tabacco",
		"11.05": "Manufacturing: Food, beverages, tabacco",
		"11.06": "Manufacturing: Food, beverages, tabacco",
		"11.07": "Manufacturing: Food, beverages, tabacco",
		"12": "Manufacturing: Food, beverages, tabacco",
		"12.0": "Manufacturing: Food, beverages, tabacco",
		"12.00": "Manufacturing: Food, beverages, tabacco",
		"13": "Manufacturing: Textiles, leather, and wood",
		"13.0": "Manufacturing: Textiles, leather, and wood",
		"13.1": "Manufacturing: Textiles, leather, and wood",
		"13.10": "Manufacturing: Textiles, leather, and wood",
		"13.2": "Manufacturing: Textiles, leather, and wood",
		"13.20": "Manufacturing: Textiles, leather, and wood",
		"13.3": "Manufacturing: Textiles, leather, and wood",
		"13.30": "Manufacturing: Textiles, leather, and wood",
		"13.9": "Manufacturing: Textiles, leather, and wood",
		"13.91": "Manufacturing: Textiles, leather, and wood",
		"13.92": "Manufacturing: Textiles, leather, and wood",
		"13.93": "Manufacturing: Textiles, leather, and wood",
		"13.94": "Manufacturing: Textiles, leather, and wood",
		"13.95": "Manufacturing: Textiles, leather, and wood",
		"13.96": "Manufacturing: Textiles, leather, and wood",
		"13.99": "Manufacturing: Textiles, leather, and wood",
		"14": "Manufacturing: Textiles, leather, and wood",
		"14.0": "Manufacturing: Textiles, leather, and wood",
		"14.1": "Manufacturing: Textiles, leather, and wood",
		"14.11": "Manufacturing: Textiles, leather, and wood",
		"14.12": "Manufacturing: Textiles, leather, and wood",
		"14.13": "Manufacturing: Textiles, leather, and wood",
		"14.14": "Manufacturing: Textiles, leather, and wood",
		"14.19": "Manufacturing: Textiles, leather, and wood",
		"14.2": "Manufacturing: Textiles, leather, and wood",
		"14.20": "Manufacturing: Textiles, leather, and wood",
		"14.3": "Manufacturing: Textiles, leather, and wood",
		"14.31": "Manufacturing: Textiles, leather, and wood",
		"14.39": "Manufacturing: Textiles, leather, and wood",
		"15": "Manufacturing: Textiles, leather, and wood",
		"15.0": "Manufacturing: Textiles, leather, and wood",
		"15.1": "Manufacturing: Textiles, leather, and wood",
		"15.11": "Manufacturing: Textiles, leather, and wood",
		"15.12": "Manufacturing: Textiles, leather, and wood",
		"15.2": "Manufacturing: Textiles, leather, and wood",
		"15.20": "Manufacturing: Textiles, leather, and wood",
		"16": "Manufacturing: Textiles, leather, and wood",
		"16.0": "Manufacturing: Textiles, leather, and wood",
		"16.1": "Manufacturing: Textiles, leather, and wood",
		"16.10": "Manufacturing: Textiles, leather, and wood",
		"16.2": "Manufacturing: Textiles, leather, and wood",
		"16.21": "Manufacturing: Textiles, leather, and wood",
		"16.22": "Manufacturing: Textiles, leather, and wood",
		"16.23": "Manufacturing: Textiles, leather, and wood",
		"16.24": "Manufacturing: Textiles, leather, and wood",
		"16.29": "Manufacturing: Textiles, leather, and wood",
		"17": "Manufacturing: Paper and printing",
		"17.0": "Manufacturing: Paper and printing",
		"17.1": "Manufacturing: Paper and printing",
		"17.11": "Manufacturing: Paper and printing",
		"17.12": "Manufacturing: Paper and printing",
		"17.2": "Manufacturing: Paper and printing",
		"17.21": "Manufacturing: Paper and printing",
		"17.22": "Manufacturing: Paper and printing",
		"17.23": "Manufacturing: Paper and printing",
		"17.24": "Manufacturing: Paper and printing",
		"17.29": "Manufacturing: Paper and printing",
		"18": "Manufacturing: Paper and printing",
		"18.0": "Manufacturing: Paper and printing",
		"18.1": "Manufacturing: Paper and printing",
		"18.11": "Manufacturing: Paper and printing",
		"18.12": "Manufacturing: Paper and printing",
		"18.13": "Manufacturing: Paper and printing",
		"18.14": "Manufacturing: Paper and printing",
		"18.2": "Manufacturing: Paper and printing",
		"18.20": "Manufacturing: Paper and printing",
		"19": "Manufacturing: Refineries, chemicals, and  pharmaceuticals",
		"19.0": "Manufacturing: Refineries, chemicals, and  pharmaceuticals",
		"19.1": "Manufacturing: Refineries, chemicals, and  pharmaceuticals",
		"19.10": "Manufacturing: Refineries, chemicals, and  pharmaceuticals",
		"19.2": "Manufacturing: Refineries, chemicals, and  pharmaceuticals",
		"19.20": "Manufacturing: Refineries, chemicals, and  pharmaceuticals",
		"20": "Manufacturing: Refineries, chemicals, and  pharmaceuticals",
		"20.0": "Manufacturing: Refineries, chemicals, and  pharmaceuticals",
		"20.1": "Manufacturing: Refineries, chemicals, and  pharmaceuticals",
		"20.11": "Manufacturing: Refineries, chemicals, and  pharmaceuticals",
		"20.12": "Manufacturing: Refineries, chemicals, and  pharmaceuticals",
		"20.13": "Manufacturing: Refineries, chemicals, and  pharmaceuticals",
		"20.14": "Manufacturing: Refineries, chemicals, and  pharmaceuticals",
		"20.15": "Manufacturing: Refineries, chemicals, and  pharmaceuticals",
		"20.16": "Manufacturing: Refineries, chemicals, and  pharmaceuticals",
		"20.17": "Manufacturing: Refineries, chemicals, and  pharmaceuticals",
		"20.2": "Manufacturing: Refineries, chemicals, and  pharmaceuticals",
		"20.20": "Manufacturing: Refineries, chemicals, and  pharmaceuticals",
		"20.3": "Manufacturing: Refineries, chemicals, and  pharmaceuticals",
		"20.30": "Manufacturing: Refineries, chemicals, and  pharmaceuticals",
		"20.4": "Manufacturing: Refineries, chemicals, and  pharmaceuticals",
		"20.41": "Manufacturing: Refineries, chemicals, and  pharmaceuticals",
		"20.42": "Manufacturing: Refineries, chemicals, and  pharmaceuticals",
		"20.5": "Manufacturing: Refineries, chemicals, and  pharmaceuticals",
		"20.51": "Manufacturing: Refineries, chemicals, and  pharmaceuticals",
		"20.52": "Manufacturing: Refineries, chemicals, and  pharmaceuticals",
		"20.53": "Manufacturing: Refineries, chemicals, and  pharmaceuticals",
		"20.59": "Manufacturing: Refineries, chemicals, and  pharmaceuticals",
		"20.6": "Manufacturing: Refineries, chemicals, and  pharmaceuticals",
		"20.60": "Manufacturing: Refineries, chemicals, and  pharmaceuticals",
		"21": "Manufacturing: Refineries, chemicals, and  pharmaceuticals",
		"21.0": "Manufacturing: Refineries, chemicals, and  pharmaceuticals",
		"21.1": "Manufacturing: Refineries, chemicals, and  pharmaceuticals",
		"21.10": "Manufacturing: Refineries, chemicals, and  pharmaceuticals",
		"21.2": "Manufacturing: Refineries, chemicals, and  pharmaceuticals",
		"21.20": "Manufacturing: Refineries, chemicals, and  pharmaceuticals",
		"22": "Manufacturing: Refineries, chemicals, and  pharmaceuticals",
		"22.0": "Manufacturing: Refineries, chemicals, and  pharmaceuticals",
		"22.1": "Manufacturing: Refineries, chemicals, and  pharmaceuticals",
		"22.11": "Manufacturing: Refineries, chemicals, and  pharmaceuticals",
		"22.19": "Manufacturing: Refineries, chemicals, and  pharmaceuticals",
		"22.2": "Manufacturing: Refineries, chemicals, and  pharmaceuticals",
		"22.21": "Manufacturing: Refineries, chemicals, and  pharmaceuticals",
		"22.22": "Manufacturing: Refineries, chemicals, and  pharmaceuticals",
		"22.23": "Manufacturing: Refineries, chemicals, and  pharmaceuticals",
		"22.29": "Manufacturing: Refineries, chemicals, and  pharmaceuticals",
		"23": "Manufacturing: Glas, ceramic, and stones",
		"23.0": "Manufacturing: Glas, ceramic, and stones",
		"23.1": "Manufacturing: Glas, ceramic, and stones",
		"23.11": "Manufacturing: Glas, ceramic, and stones",
		"23.12": "Manufacturing: Glas, ceramic, and stones",
		"23.13": "Manufacturing: Glas, ceramic, and stones",
		"23.14": "Manufacturing: Glas, ceramic, and stones",
		"23.19": "Manufacturing: Glas, ceramic, and stones",
		"23.2": "Manufacturing: Glas, ceramic, and stones",
		"23.20": "Manufacturing: Glas, ceramic, and stones",
		"23.3": "Manufacturing: Glas, ceramic, and stones",
		"23.31": "Manufacturing: Glas, ceramic, and stones",
		"23.32": "Manufacturing: Glas, ceramic, and stones",
		"23.4": "Manufacturing: Glas, ceramic, and stones",
		"23.41": "Manufacturing: Glas, ceramic, and stones",
		"23.42": "Manufacturing: Glas, ceramic, and stones",
		"23.43": "Manufacturing: Glas, ceramic, and stones",
		"23.44": "Manufacturing: Glas, ceramic, and stones",
		"23.49": "Manufacturing: Glas, ceramic, and stones",
		"23.5": "Manufacturing: Glas, ceramic, and stones",
		"23.51": "Manufacturing: Glas, ceramic, and stones",
		"23.52": "Manufacturing: Glas, ceramic, and stones",
		"23.6": "Manufacturing: Glas, ceramic, and stones",
		"23.61": "Manufacturing: Glas, ceramic, and stones",
		"23.62": "Manufacturing: Glas, ceramic, and stones",
		"23.63": "Manufacturing: Glas, ceramic, and stones",
		"23.64": "Manufacturing: Glas, ceramic, and stones",
		"23.65": "Manufacturing: Glas, ceramic, and stones",
		"23.69": "Manufacturing: Glas, ceramic, and stones",
		"23.7": "Manufacturing: Glas, ceramic, and stones",
		"23.70": "Manufacturing: Glas, ceramic, and stones",
		"23.9": "Manufacturing: Glas, ceramic, and stones",
		"23.91": "Manufacturing: Glas, ceramic, and stones",
		"23.99": "Manufacturing: Glas, ceramic, and stones",
		"24": "Manufacturing: Metals and machineries",
		"24.0": "Manufacturing: Metals and machineries",
		"24.1": "Manufacturing: Metals and machineries",
		"24.10": "Manufacturing: Metals and machineries",
		"24.2": "Manufacturing: Metals and machineries",
		"24.20": "Manufacturing: Metals and machineries",
		"24.3": "Manufacturing: Metals and machineries",
		"24.31": "Manufacturing: Metals and machineries",
		"24.32": "Manufacturing: Metals and machineries",
		"24.33": "Manufacturing: Metals and machineries",
		"24.34": "Manufacturing: Metals and machineries",
		"24.4": "Manufacturing: Metals and machineries",
		"24.41": "Manufacturing: Metals and machineries",
		"24.42": "Manufacturing: Metals and machineries",
		"24.43": "Manufacturing: Metals and machineries",
		"24.44": "Manufacturing: Metals and machineries",
		"24.45": "Manufacturing: Metals and machineries",
		"24.46": "Manufacturing: Metals and machineries",
		"24.5": "Manufacturing: Metals and machineries",
		"24.51": "Manufacturing: Metals and machineries",
		"24.52": "Manufacturing: Metals and machineries",
		"24.53": "Manufacturing: Metals and machineries",
		"24.54": "Manufacturing: Metals and machineries",
		"25": "Manufacturing: Metals and machineries",
		"25.0": "Manufacturing: Metals and machineries",
		"25.1": "Manufacturing: Metals and machineries",
		"25.11": "Manufacturing: Metals and machineries",
		"25.12": "Manufacturing: Metals and machineries",
		"25.2": "Manufacturing: Metals and machineries",
		"25.21": "Manufacturing: Metals and machineries",
		"25.29": "Manufacturing: Metals and machineries",
		"25.3": "Manufacturing: Metals and machineries",
		"25.30": "Manufacturing: Metals and machineries",
		"25.4": "Manufacturing: Metals and machineries",
		"25.40": "Manufacturing: Metals and machineries",
		"25.5": "Manufacturing: Metals and machineries",
		"25.50": "Manufacturing: Metals and machineries",
		"25.6": "Manufacturing: Metals and machineries",
		"25.61": "Manufacturing: Metals and machineries",
		"25.62": "Manufacturing: Metals and machineries",
		"25.7": "Manufacturing: Metals and machineries",
		"25.71": "Manufacturing: Metals and machineries",
		"25.72": "Manufacturing: Metals and machineries",
		"25.73": "Manufacturing: Metals and machineries",
		"25.9": "Manufacturing: Metals and machineries",
		"25.91": "Manufacturing: Metals and machineries",
		"25.92": "Manufacturing: Metals and machineries",
		"25.93": "Manufacturing: Metals and machineries",
		"25.94": "Manufacturing: Metals and machineries",
		"25.99": "Manufacturing: Metals and machineries",
		"26": "Manufacturing: Metals and machineries",
		"26.0": "Manufacturing: Metals and machineries",
		"26.1": "Manufacturing: Metals and machineries",
		"26.11": "Manufacturing: Metals and machineries",
		"26.12": "Manufacturing: Metals and machineries",
		"26.2": "Manufacturing: Metals and machineries",
		"26.20": "Manufacturing: Metals and machineries",
		"26.3": "Manufacturing: Metals and machineries",
		"26.30": "Manufacturing: Metals and machineries",
		"26.4": "Manufacturing: Metals and machineries",
		"26.40": "Manufacturing: Metals and machineries",
		"26.5": "Manufacturing: Metals and machineries",
		"26.51": "Manufacturing: Metals and machineries",
		"26.52": "Manufacturing: Metals and machineries",
		"26.6": "Manufacturing: Metals and machineries",
		"26.60": "Manufacturing: Metals and machineries",
		"26.7": "Manufacturing: Metals and machineries",
		"26.70": "Manufacturing: Metals and machineries",
		"26.8": "Manufacturing: Metals and machineries",
		"26.80": "Manufacturing: Metals and machineries",
		"27": "Manufacturing: Metals and machineries",
		"27.0": "Manufacturing: Metals and machineries",
		"27.1": "Manufacturing: Metals and machineries",
		"27.11": "Manufacturing: Metals and machineries",
		"27.12": "Manufacturing: Metals and machineries",
		"27.2": "Manufacturing: Metals and machineries",
		"27.20": "Manufacturing: Metals and machineries",
		"27.3": "Manufacturing: Metals and machineries",
		"27.31": "Manufacturing: Metals and machineries",
		"27.32": "Manufacturing: Metals and machineries",
		"27.33": "Manufacturing: Metals and machineries",
		"27.4": "Manufacturing: Metals and machineries",
		"27.40": "Manufacturing: Metals and machineries",
		"27.5": "Manufacturing: Metals and machineries",
		"27.51": "Manufacturing: Metals and machineries",
		"27.52": "Manufacturing: Metals and machineries",
		"27.9": "Manufacturing: Metals and machineries",
		"27.90": "Manufacturing: Metals and machineries",
		"28": "Manufacturing: Metals and machineries",
		"28.0": "Manufacturing: Metals and machineries",
		"28.1": "Manufacturing: Metals and machineries",
		"28.11": "Manufacturing: Metals and machineries",
		"28.12": "Manufacturing: Metals and machineries",
		"28.13": "Manufacturing: Metals and machineries",
		"28.14": "Manufacturing: Metals and machineries",
		"28.15": "Manufacturing: Metals and machineries",
		"28.2": "Manufacturing: Metals and machineries",
		"28.21": "Manufacturing: Metals and machineries",
		"28.22": "Manufacturing: Metals and machineries",
		"28.23": "Manufacturing: Metals and machineries",
		"28.24": "Manufacturing: Metals and machineries",
		"28.25": "Manufacturing: Metals and machineries",
		"28.29": "Manufacturing: Metals and machineries",
		"28.3": "Manufacturing: Metals and machineries",
		"28.30": "Manufacturing: Metals and machineries",
		"28.4": "Manufacturing: Metals and machineries",
		"28.41": "Manufacturing: Metals and machineries",
		"28.49": "Manufacturing: Metals and machineries",
		"28.9": "Manufacturing: Metals and machineries",
		"28.91": "Manufacturing: Metals and machineries",
		"28.92": "Manufacturing: Metals and machineries",
		"28.93": "Manufacturing: Metals and machineries",
		"28.94": "Manufacturing: Metals and machineries",
		"28.95": "Manufacturing: Metals and machineries",
		"28.96": "Manufacturing: Metals and machineries",
		"28.99": "Manufacturing: Metals and machineries",
		"29": "Manufacturing: Cars and other",
		"29.0": "Manufacturing: Cars and other",
		"29.1": "Manufacturing: Cars and other",
		"29.10": "Manufacturing: Cars and other",
		"29.2": "Manufacturing: Cars and other",
		"29.20": "Manufacturing: Cars and other",
		"29.3": "Manufacturing: Cars and other",
		"29.31": "Manufacturing: Cars and other",
		"29.32": "Manufacturing: Cars and other",
		"30": "Manufacturing: Cars and other",
		"30.0": "Manufacturing: Cars and other",
		"30.1": "Manufacturing: Cars and other",
		"30.11": "Manufacturing: Cars and other",
		"30.12": "Manufacturing: Cars and other",
		"30.2": "Manufacturing: Cars and other",
		"30.20": "Manufacturing: Cars and other",
		"30.3": "Manufacturing: Cars and other",
		"30.30": "Manufacturing: Cars and other",
		"30.4": "Manufacturing: Cars and other",
		"30.40": "Manufacturing: Cars and other",
		"30.9": "Manufacturing: Cars and other",
		"30.91": "Manufacturing: Cars and other",
		"30.92": "Manufacturing: Cars and other",
		"30.99": "Manufacturing: Cars and other",
		"31": "Manufacturing: Cars and other",
		"31.0": "Manufacturing: Cars and other",
		"31.01": "Manufacturing: Cars and other",
		"31.02": "Manufacturing: Cars and other",
		"31.03": "Manufacturing: Cars and other",
		"31.09": "Manufacturing: Cars and other",
		"32": "Manufacturing: Cars and other",
		"32.0": "Manufacturing: Cars and other",
		"32.1": "Manufacturing: Cars and other",
		"32.11": "Manufacturing: Cars and other",
		"32.12": "Manufacturing: Cars and other",
		"32.13": "Manufacturing: Cars and other",
		"32.2": "Manufacturing: Cars and other",
		"32.20": "Manufacturing: Cars and other",
		"32.3": "Manufacturing: Cars and other",
		"32.30": "Manufacturing: Cars and other",
		"32.4": "Manufacturing: Cars and other",
		"32.40": "Manufacturing: Cars and other",
		"32.5": "Manufacturing: Cars and other",
		"32.50": "Manufacturing: Cars and other",
		"32.9": "Manufacturing: Cars and other",
		"32.91": "Manufacturing: Cars and other",
		"32.99": "Manufacturing: Cars and other",
		"33": "Manufacturing: Cars and other",
		"33.0": "Manufacturing: Cars and other",
		"33.1": "Manufacturing: Cars and other",
		"33.11": "Manufacturing: Cars and other",
		"33.12": "Manufacturing: Cars and other",
		"33.13": "Manufacturing: Cars and other",
		"33.14": "Manufacturing: Cars and other",
		"33.15": "Manufacturing: Cars and other",
		"33.16": "Manufacturing: Cars and other",
		"33.17": "Manufacturing: Cars and other",
		"33.19": "Manufacturing: Cars and other",
		"33.2": "Manufacturing: Cars and other",
		"33.20": "Manufacturing: Cars and other",
		"35": "Energy: General",
		"35.0": "Energy: General",
		"35.1": "Energy: Electricity generation",
		"35.11": "Energy: Electricity generation",
		"35.12": "Energy: Electricity generation",
		"35.13": "Energy: Electricity generation",
		"35.14": "Energy: Electricity generation",
		"35.2": "Energy: Gas production and distribution",
		"35.21": "Energy: Gas production and distribution",
		"35.22": "Energy: Gas production and distribution",
		"35.23": "Energy: Gas production and distribution",
		"35.3": "Energy: Steam and air conditioning supply",
		"35.30": "Energy: Steam and air conditioning supply",
		"36": "Construction and services",
		"36.0": "Construction and services",
		"36.00": "Construction and services",
		"37": "Construction and services",
		"37.0": "Construction and services",
		"37.00": "Construction and services",
		"38": "Construction and services",
		"38.0": "Construction and services",
		"38.1": "Construction and services",
		"38.11": "Construction and services",
		"38.12": "Construction and services",
		"38.2": "Construction and services",
		"38.21": "Construction and services",
		"38.22": "Construction and services",
		"38.3": "Construction and services",
		"38.31": "Construction and services",
		"38.32": "Construction and services",
		"39": "Construction and services",
		"39.0": "Construction and services",
		"39.00": "Construction and services",
		"41": "Construction and services",
		"41.0": "Construction and services",
		"41.1": "Construction and services",
		"41.10": "Construction and services",
		"41.2": "Construction and services",
		"41.20": "Construction and services",
		"42": "Construction and services",
		"42.0": "Construction and services",
		"42.1": "Construction and services",
		"42.11": "Construction and services",
		"42.12": "Construction and services",
		"42.13": "Construction and services",
		"42.2": "Construction and services",
		"42.21": "Construction and services",
		"42.22": "Construction and services",
		"42.9": "Construction and services",
		"42.91": "Construction and services",
		"42.99": "Construction and services",
		"43": "Construction and services",
		"43.0": "Construction and services",
		"43.1": "Construction and services",
		"43.11": "Construction and services",
		"43.12": "Construction and services",
		"43.13": "Construction and services",
		"43.2": "Construction and services",
		"43.21": "Construction and services",
		"43.22": "Construction and services",
		"43.29": "Construction and services",
		"43.3": "Construction and services",
		"43.31": "Construction and services",
		"43.32": "Construction and services",
		"43.33": "Construction and services",
		"43.34": "Construction and services",
		"43.39": "Construction and services",
		"43.9": "Construction and services",
		"43.91": "Construction and services",
		"43.99": "Construction and services",
		"45": "Construction and services",
		"45.0": "Construction and services",
		"45.1": "Construction and services",
		"45.11": "Construction and services",
		"45.19": "Construction and services",
		"45.2": "Construction and services",
		"45.20": "Construction and services",
		"45.3": "Construction and services",
		"45.31": "Construction and services",
		"45.32": "Construction and services",
		"45.4": "Construction and services",
		"45.40": "Construction and services",
		"46": "Construction and services",
		"46.0": "Construction and services",
		"46.1": "Construction and services",
		"46.11": "Construction and services",
		"46.12": "Construction and services",
		"46.13": "Construction and services",
		"46.14": "Construction and services",
		"46.15": "Construction and services",
		"46.16": "Construction and services",
		"46.17": "Construction and services",
		"46.18": "Construction and services",
		"46.19": "Construction and services",
		"46.2": "Construction and services",
		"46.21": "Construction and services",
		"46.22": "Construction and services",
		"46.23": "Construction and services",
		"46.24": "Construction and services",
		"46.3": "Construction and services",
		"46.31": "Construction and services",
		"46.32": "Construction and services",
		"46.33": "Construction and services",
		"46.34": "Construction and services",
		"46.35": "Construction and services",
		"46.36": "Construction and services",
		"46.37": "Construction and services",
		"46.38": "Construction and services",
		"46.39": "Construction and services",
		"46.4": "Construction and services",
		"46.41": "Construction and services",
		"46.42": "Construction and services",
		"46.43": "Construction and services",
		"46.44": "Construction and services",
		"46.45": "Construction and services",
		"46.46": "Construction and services",
		"46.47": "Construction and services",
		"46.48": "Construction and services",
		"46.49": "Construction and services",
		"46.5": "Construction and services",
		"46.51": "Construction and services",
		"46.52": "Construction and services",
		"46.6": "Construction and services",
		"46.61": "Construction and services",
		"46.62": "Construction and services",
		"46.63": "Construction and services",
		"46.64": "Construction and services",
		"46.65": "Construction and services",
		"46.66": "Construction and services",
		"46.69": "Construction and services",
		"46.7": "Construction and services",
		"46.71": "Construction and services",
		"46.72": "Construction and services",
		"46.73": "Construction and services",
		"46.74": "Construction and services",
		"46.75": "Construction and services",
		"46.76": "Construction and services",
		"46.77": "Construction and services",
		"46.9": "Construction and services",
		"46.90": "Construction and services",
		"47": "Construction and services",
		"47.0": "Construction and services",
		"47.1": "Construction and services",
		"47.11": "Construction and services",
		"47.19": "Construction and services",
		"47.2": "Construction and services",
		"47.21": "Construction and services",
		"47.22": "Construction and services",
		"47.23": "Construction and services",
		"47.24": "Construction and services",
		"47.25": "Construction and services",
		"47.26": "Construction and services",
		"47.29": "Construction and services",
		"47.3": "Construction and services",
		"47.30": "Construction and services",
		"47.4": "Construction and services",
		"47.41": "Construction and services",
		"47.42": "Construction and services",
		"47.43": "Construction and services",
		"47.5": "Construction and services",
		"47.51": "Construction and services",
		"47.52": "Construction and services",
		"47.53": "Construction and services",
		"47.54": "Construction and services",
		"47.59": "Construction and services",
		"47.6": "Construction and services",
		"47.61": "Construction and services",
		"47.62": "Construction and services",
		"47.63": "Construction and services",
		"47.64": "Construction and services",
		"47.65": "Construction and services",
		"47.7": "Construction and services",
		"47.71": "Construction and services",
		"47.72": "Construction and services",
		"47.73": "Construction and services",
		"47.74": "Construction and services",
		"47.75": "Construction and services",
		"47.76": "Construction and services",
		"47.77": "Construction and services",
		"47.78": "Construction and services",
		"47.79": "Construction and services",
		"47.8": "Construction and services",
		"47.81": "Construction and services",
		"47.82": "Construction and services",
		"47.89": "Construction and services",
		"47.9": "Construction and services",
		"47.91": "Construction and services",
		"47.99": "Construction and services",
		"49": "Construction and services",
		"49.0": "Construction and services",
		"49.1": "Construction and services",
		"49.10": "Construction and services",
		"49.2": "Construction and services",
		"49.20": "Construction and services",
		"49.3": "Construction and services",
		"49.31": "Construction and services",
		"49.32": "Construction and services",
		"49.39": "Construction and services",
		"49.4": "Construction and services",
		"49.41": "Construction and services",
		"49.42": "Construction and services",
		"49.5": "Construction and services",
		"49.50": "Construction and services",
		"50": "Construction and services",
		"50.0": "Construction and services",
		"50.1": "Construction and services",
		"50.10": "Construction and services",
		"50.2": "Construction and services",
		"50.20": "Construction and services",
		"50.3": "Construction and services",
		"50.30": "Construction and services",
		"50.4": "Construction and services",
		"50.40": "Construction and services",
		"51": "Air transport",
		"51.0": "Air transport",
		"51.1": "Air transport",
		"51.10": "Air transport",
		"51.2": "Air transport",
		"51.21": "Air transport",
		"51.22": "Air transport",
		"52": "Construction and services",
		"52.0": "Construction and services",
		"52.1": "Construction and services",
		"52.10": "Construction and services",
		"52.2": "Construction and services",
		"52.21": "Construction and services",
		"52.22": "Construction and services",
		"52.23": "Construction and services",
		"52.24": "Construction and services",
		"52.29": "Construction and services",
		"53": "Construction and services",
		"53.0": "Construction and services",
		"53.1": "Construction and services",
		"53.10": "Construction and services",
		"53.2": "Construction and services",
		"53.20": "Construction and services",
		"55": "Construction and services",
		"55.0": "Construction and services",
		"55.1": "Construction and services",
		"55.10": "Construction and services",
		"55.2": "Construction and services",
		"55.20": "Construction and services",
		"55.3": "Construction and services",
		"55.30": "Construction and services",
		"55.9": "Construction and services",
		"55.90": "Construction and services",
		"56": "Construction and services",
		"56.0": "Construction and services",
		"56.1": "Construction and services",
		"56.10": "Construction and services",
		"56.2": "Construction and services",
		"56.21": "Construction and services",
		"56.29": "Construction and services",
		"56.3": "Construction and services",
		"56.30": "Construction and services",
		"58": "Construction and services",
		"58.0": "Construction and services",
		"58.1": "Construction and services",
		"58.11": "Construction and services",
		"58.12": "Construction and services",
		"58.13": "Construction and services",
		"58.14": "Construction and services",
		"58.19": "Construction and services",
		"58.2": "Construction and services",
		"58.21": "Construction and services",
		"58.29": "Construction and services",
		"59": "Construction and services",
		"59.0": "Construction and services",
		"59.1": "Construction and services",
		"59.11": "Construction and services",
		"59.12": "Construction and services",
		"59.13": "Construction and services",
		"59.14": "Construction and services",
		"59.2": "Construction and services",
		"59.20": "Construction and services",
		"60": "Construction and services",
		"60.0": "Construction and services",
		"60.1": "Construction and services",
		"60.10": "Construction and services",
		"60.2": "Construction and services",
		"60.20": "Construction and services",
		"61": "Construction and services",
		"61.0": "Construction and services",
		"61.1": "Construction and services",
		"61.10": "Construction and services",
		"61.2": "Construction and services",
		"61.20": "Construction and services",
		"61.3": "Construction and services",
		"61.30": "Construction and services",
		"61.9": "Construction and services",
		"61.90": "Construction and services",
		"62": "Construction and services",
		"62.0": "Construction and services",
		"62.01": "Construction and services",
		"62.02": "Construction and services",
		"62.03": "Construction and services",
		"62.09": "Construction and services",
		"63": "Construction and services",
		"63.0": "Construction and services",
		"63.1": "Construction and services",
		"63.11": "Construction and services",
		"63.12": "Construction and services",
		"63.9": "Construction and services",
		"63.91": "Construction and services",
		"63.99": "Construction and services",
		"64": "Construction and services",
		"64.0": "Construction and services",
		"64.1": "Construction and services",
		"64.11": "Construction and services",
		"64.19": "Construction and services",
		"64.2": "Construction and services",
		"64.20": "Construction and services",
		"64.3": "Construction and services",
		"64.30": "Construction and services",
		"64.9": "Construction and services",
		"64.91": "Construction and services",
		"64.92": "Construction and services",
		"64.99": "Construction and services",
		"65": "Construction and services",
		"65.0": "Construction and services",
		"65.1": "Construction and services",
		"65.11": "Construction and services",
		"65.12": "Construction and services",
		"65.2": "Construction and services",
		"65.20": "Construction and services",
		"65.3": "Construction and services",
		"65.30": "Construction and services",
		"66": "Construction and services",
		"66.0": "Construction and services",
		"66.1": "Construction and services",
		"66.11": "Construction and services",
		"66.12": "Construction and services",
		"66.19": "Construction and services",
		"66.2": "Construction and services",
		"66.21": "Construction and services",
		"66.22": "Construction and services",
		"66.29": "Construction and services",
		"66.3": "Construction and services",
		"66.30": "Construction and services",
		"68": "Construction and services",
		"68.0": "Construction and services",
		"68.1": "Construction and services",
		"68.10": "Construction and services",
		"68.2": "Construction and services",
		"68.20": "Construction and services",
		"68.3": "Construction and services",
		"68.31": "Construction and services",
		"68.32": "Construction and services",
		"69": "Construction and services",
		"69.0": "Construction and services",
		"69.1": "Construction and services",
		"69.10": "Construction and services",
		"69.2": "Construction and services",
		"69.20": "Construction and services",
		"70": "Construction and services",
		"70.0": "Construction and services",
		"70.1": "Construction and services",
		"70.10": "Construction and services",
		"70.2": "Construction and services",
		"70.21": "Construction and services",
		"70.22": "Construction and services",
		"71": "Construction and services",
		"71.0": "Construction and services",
		"71.1": "Construction and services",
		"71.11": "Construction and services",
		"71.12": "Construction and services",
		"71.2": "Construction and services",
		"71.20": "Construction and services",
		"72": "Construction and services",
		"72.0": "Construction and services",
		"72.1": "Construction and services",
		"72.11": "Construction and services",
		"72.19": "Construction and services",
		"72.2": "Construction and services",
		"72.20": "Construction and services",
		"73": "Construction and services",
		"73.0": "Construction and services",
		"73.1": "Construction and services",
		"73.11": "Construction and services",
		"73.12": "Construction and services",
		"73.2": "Construction and services",
		"73.20": "Construction and services",
		"74": "Construction and services",
		"74.0": "Construction and services",
		"74.1": "Construction and services",
		"74.10": "Construction and services",
		"74.2": "Construction and services",
		"74.20": "Construction and services",
		"74.3": "Construction and services",
		"74.30": "Construction and services",
		"74.9": "Construction and services",
		"74.90": "Construction and services",
		"75": "Construction and services",
		"75.0": "Construction and services",
		"75.00": "Construction and services",
		"77": "Construction and services",
		"77.0": "Construction and services",
		"77.1": "Construction and services",
		"77.11": "Construction and services",
		"77.12": "Construction and services",
		"77.2": "Construction and services",
		"77.21": "Construction and services",
		"77.22": "Construction and services",
		"77.29": "Construction and services",
		"77.3": "Construction and services",
		"77.31": "Construction and services",
		"77.32": "Construction and services",
		"77.33": "Construction and services",
		"77.34": "Construction and services",
		"77.35": "Construction and services",
		"77.39": "Construction and services",
		"77.4": "Construction and services",
		"77.40": "Construction and services",
		"78": "Construction and services",
		"78.0": "Construction and services",
		"78.1": "Construction and services",
		"78.10": "Construction and services",
		"78.2": "Construction and services",
		"78.20": "Construction and services",
		"78.3": "Construction and services",
		"78.30": "Construction and services",
		"79": "Construction and services",
		"79.0": "Construction and services",
		"79.1": "Construction and services",
		"79.11": "Construction and services",
		"79.12": "Construction and services",
		"79.9": "Construction and services",
		"79.90": "Construction and services",
		"80": "Construction and services",
		"80.0": "Construction and services",
		"80.1": "Construction and services",
		"80.10": "Construction and services",
		"80.2": "Construction and services",
		"80.20": "Construction and services",
		"80.3": "Construction and services",
		"80.30": "Construction and services",
		"81": "Construction and services",
		"81.0": "Construction and services",
		"81.1": "Construction and services",
		"81.10": "Construction and services",
		"81.2": "Construction and services",
		"81.21": "Construction and services",
		"81.22": "Construction and services",
		"81.29": "Construction and services",
		"81.3": "Construction and services",
		"81.30": "Construction and services",
		"82": "Construction and services",
		"82.0": "Construction and services",
		"82.1": "Construction and services",
		"82.11": "Construction and services",
		"82.19": "Construction and services",
		"82.2": "Construction and services",
		"82.20": "Construction and services",
		"82.3": "Construction and services",
		"82.30": "Construction and services",
		"82.9": "Construction and services",
		"82.91": "Construction and services",
		"82.92": "Construction and services",
		"82.99": "Construction and services",
		"84": "Construction and services",
		"84.0": "Construction and services",
		"84.1": "Construction and services",
		"84.11": "Construction and services",
		"84.12": "Construction and services",
		"84.13": "Construction and services",
		"84.2": "Construction and services",
		"84.21": "Construction and services",
		"84.22": "Construction and services",
		"84.23": "Construction and services",
		"84.24": "Construction and services",
		"84.25": "Construction and services",
		"84.3": "Construction and services",
		"84.30": "Construction and services",
		"85": "Construction and services",
		"85.0": "Construction and services",
		"85.1": "Construction and services",
		"85.10": "Construction and services",
		"85.2": "Construction and services",
		"85.20": "Construction and services",
		"85.3": "Construction and services",
		"85.31": "Construction and services",
		"85.32": "Construction and services",
		"85.4": "Construction and services",
		"85.41": "Construction and services",
		"85.42": "Construction and services",
		"85.5": "Construction and services",
		"85.51": "Construction and services",
		"85.52": "Construction and services",
		"85.53": "Construction and services",
		"85.59": "Construction and services",
		"85.6": "Construction and services",
		"85.60": "Construction and services",
		"86": "Construction and services",
		"86.0": "Construction and services",
		"86.1": "Construction and services",
		"86.10": "Construction and services",
		"86.2": "Construction and services",
		"86.21": "Construction and services",
		"86.22": "Construction and services",
		"86.23": "Construction and services",
		"86.9": "Construction and services",
		"86.90": "Construction and services",
		"87": "Construction and services",
		"87.0": "Construction and services",
		"87.1": "Construction and services",
		"87.10": "Construction and services",
		"87.2": "Construction and services",
		"87.20": "Construction and services",
		"87.3": "Construction and services",
		"87.30": "Construction and services",
		"87.9": "Construction and services",
		"87.90": "Construction and services",
		"88": "Construction and services",
		"88.0": "Construction and services",
		"88.1": "Construction and services",
		"88.10": "Construction and services",
		"88.9": "Construction and services",
		"88.91": "Construction and services",
		"88.99": "Construction and services",
		"90": "Construction and services",
		"90.0": "Construction and services",
		"90.01": "Construction and services",
		"90.02": "Construction and services",
		"90.03": "Construction and services",
		"90.04": "Construction and services",
		"91": "Construction and services",
		"91.0": "Construction and services",
		"91.01": "Construction and services",
		"91.02": "Construction and services",
		"91.03": "Construction and services",
		"91.04": "Construction and services",
		"92": "Construction and services",
		"92.0": "Construction and services",
		"92.00": "Construction and services",
		"93": "Construction and services",
		"93.0": "Construction and services",
		"93.1": "Construction and services",
		"93.11": "Construction and services",
		"93.12": "Construction and services",
		"93.13": "Construction and services",
		"93.19": "Construction and services",
		"93.2": "Construction and services",
		"93.21": "Construction and services",
		"93.29": "Construction and services",
		"94": "Construction and services",
		"94.0": "Construction and services",
		"94.1": "Construction and services",
		"94.11": "Construction and services",
		"94.12": "Construction and services",
		"94.2": "Construction and services",
		"94.20": "Construction and services",
		"94.9": "Construction and services",
		"94.91": "Construction and services",
		"94.92": "Construction and services",
		"94.99": "Construction and services",
		"95": "Construction and services",
		"95.0": "Construction and services",
		"95.1": "Construction and services",
		"95.11": "Construction and services",
		"95.12": "Construction and services",
		"95.2": "Construction and services",
		"95.21": "Construction and services",
		"95.22": "Construction and services",
		"95.23": "Construction and services",
		"95.24": "Construction and services",
		"95.25": "Construction and services",
		"95.29": "Construction and services",
		"96": "Construction and services",
		"96.0": "Construction and services",
		"96.01": "Construction and services",
		"96.02": "Construction and services",
		"96.03": "Construction and services",
		"96.04": "Construction and services",
		"96.09": "Construction and services",
		"97": "Construction and services",
		"97.0": "Construction and services",
		"97.00": "Construction and services",
		"98": "Construction and services",
		"98.0": "Construction and services",
		"98.1": "Construction and services",
		"98.10": "Construction and services",
		"98.2": "Construction and services",
		"98.20": "Construction and services",
		"99": "Construction and services",
		"99.0": "Construction and services",
		"99.00": "Construction and services"}

map_nace_inv = {}
for key, val in map_nace.items():
    map_nace_inv[val] = map_nace_inv.get(val, []) + [key]